// Generated by Apple Swift version 4.2.1 (swiftlang-1000.11.42 clang-1000.11.45.1)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if __has_feature(modules)
@import CoreGraphics;
@import Foundation;
@import UIKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="fluigSDKUi",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@class NSCoder;

SWIFT_CLASS("_TtC10fluigSDKUi15DirectLoginView")
@interface DirectLoginView : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end



@class UIViewController;

SWIFT_PROTOCOL("_TtP10fluigSDKUi26FluigSDKPageViewDataSource_")
@protocol FluigSDKPageViewDataSource
@optional
- (NSArray<NSString *> * _Nonnull)getStrings SWIFT_WARN_UNUSED_RESULT;
- (NSArray<UIViewController *> * _Nonnull)getViewControllers SWIFT_WARN_UNUSED_RESULT;
@end


@interface DirectLoginView (SWIFT_EXTENSION(fluigSDKUi)) <FluigSDKPageViewDataSource>
- (NSArray<UIViewController *> * _Nonnull)getViewControllers SWIFT_WARN_UNUSED_RESULT;
@end

@class UIImage;
@class UIColor;

@interface DirectLoginView (SWIFT_EXTENSION(fluigSDKUi))
@property (nonatomic) NSInteger state;
@property (nonatomic, strong) UIImage * _Nullable logoImage;
@property (nonatomic, copy) NSString * _Nullable pageControlTitle;
@property (nonatomic, strong) UIColor * _Nullable buttonFirstColor;
@property (nonatomic, strong) UIColor * _Nullable buttonLastColor;
@end


SWIFT_CLASS("_TtC10fluigSDKUi16EmailRequestView")
@interface EmailRequestView : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end




@interface EmailRequestView (SWIFT_EXTENSION(fluigSDKUi))
@property (nonatomic, strong) UIImage * _Nullable backgroundImage;
@property (nonatomic, strong) UIColor * _Nonnull backgroundFirstColor;
@property (nonatomic, strong) UIColor * _Nonnull backgroundLastColor;
@property (nonatomic, strong) UIImage * _Nullable logoImage;
@property (nonatomic, copy) NSString * _Nullable pageControlTitle;
@property (nonatomic, strong) UIImage * _Nullable textFieldIcon;
@property (nonatomic, strong) UIColor * _Nullable buttonFirstColor;
@property (nonatomic, strong) UIColor * _Nullable buttonLastColor;
@end


SWIFT_CLASS("_TtC10fluigSDKUi13EulaTermsView")
@interface EulaTermsView : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10fluigSDKUi8EulaView")
@interface EulaView : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10fluigSDKUi14FluigSDKButton")
@interface FluigSDKButton : UIButton
/// Sets the background color for the button
@property (nonatomic, strong) UIColor * _Nullable backgroundColor;
/// If informed composes with the backgroundColor to form a gradient.
@property (nonatomic, strong) UIColor * _Nullable backgroundColorEnd;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
- (void)prepareForInterfaceBuilder;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) Class _Nonnull layerClass;)
+ (Class _Nonnull)layerClass SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC10fluigSDKUi19FluigSDKLoadingView")
@interface FluigSDKLoadingView : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10fluigSDKUi17FluigSDKMediaView")
@interface FluigSDKMediaView : UIView
@property (nonatomic, strong) UIImage * _Nullable image;
/// Gradient background start color
@property (nonatomic, strong) UIColor * _Nonnull firstColor;
/// Gradient background finish color
@property (nonatomic, strong) UIColor * _Nullable lastColor;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init;
@end




@interface FluigSDKMediaView (SWIFT_EXTENSION(fluigSDKUi))
- (void)prepareForInterfaceBuilder;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) Class _Nonnull layerClass;)
+ (Class _Nonnull)layerClass SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC10fluigSDKUi16FluigSDKPageView")
@interface FluigSDKPageView : UIView
@property (nonatomic, strong) UIColor * _Nullable tintColor;
@property (nonatomic, copy) NSString * _Nullable title;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end

@class UIPageViewController;

@interface FluigSDKPageView (SWIFT_EXTENSION(fluigSDKUi)) <UIPageViewControllerDelegate>
- (void)pageViewController:(UIPageViewController * _Nonnull)pageViewController didFinishAnimating:(BOOL)finished previousViewControllers:(NSArray<UIViewController *> * _Nonnull)previousViewControllers transitionCompleted:(BOOL)completed;
@end


@interface FluigSDKPageView (SWIFT_EXTENSION(fluigSDKUi)) <UIPageViewControllerDataSource>
- (UIViewController * _Nullable)pageViewController:(UIPageViewController * _Nonnull)pageViewController viewControllerBeforeViewController:(UIViewController * _Nonnull)viewController SWIFT_WARN_UNUSED_RESULT;
- (UIViewController * _Nullable)pageViewController:(UIPageViewController * _Nonnull)pageViewController viewControllerAfterViewController:(UIViewController * _Nonnull)viewController SWIFT_WARN_UNUSED_RESULT;
@end



SWIFT_CLASS("_TtC10fluigSDKUi17FluigSDKPopUpView")
@interface FluigSDKPopUpView : UIView
@property (nonatomic, copy) NSString * _Nonnull buttonText;
@property (nonatomic, weak) UIImage * _Nullable image;
@property (nonatomic, copy) NSString * _Nonnull message;
@property (nonatomic, strong) UIColor * _Nonnull accentColor;
@property (nonatomic, copy) NSString * _Nonnull title;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10fluigSDKUi18FluigSDKProfilePic")
@interface FluigSDKProfilePic : UIView
@property (nonatomic, strong) UIImage * _Nullable image;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
- (void)layoutSubviews;
@end


SWIFT_CLASS("_TtC10fluigSDKUi17FluigSDKTextField")
@interface FluigSDKTextField : UITextField
@property (nonatomic, weak) UIImage * _Nullable icon;
@property (nonatomic, copy) NSString * _Nullable placeholder;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (void)prepareForInterfaceBuilder;
- (CGRect)editingRectForBounds:(CGRect)bounds SWIFT_WARN_UNUSED_RESULT;
- (CGRect)textRectForBounds:(CGRect)bounds SWIFT_WARN_UNUSED_RESULT;
- (CGRect)leftViewRectForBounds:(CGRect)bounds SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC10fluigSDKUi22FluigSDKTextFieldGroup")
@interface FluigSDKTextFieldGroup : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init;
@end


SWIFT_CLASS("_TtC10fluigSDKUi18ForgotPasswordView")
@interface ForgotPasswordView : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end




@interface ForgotPasswordView (SWIFT_EXTENSION(fluigSDKUi)) <FluigSDKPageViewDataSource>
- (NSArray<NSString *> * _Nonnull)getStrings SWIFT_WARN_UNUSED_RESULT;
@end


@interface ForgotPasswordView (SWIFT_EXTENSION(fluigSDKUi))
@property (nonatomic, strong) UIImage * _Nullable backgroundImage;
@property (nonatomic, strong) UIColor * _Nonnull backgroundFirstColor;
@property (nonatomic, strong) UIColor * _Nonnull backgroundLastColor;
@property (nonatomic, strong) UIImage * _Nullable logoImage;
@property (nonatomic, copy) NSString * _Nullable pageControlTitle;
@property (nonatomic, strong) UIImage * _Nullable textFieldIcon;
@property (nonatomic, strong) UIColor * _Nullable buttonFirstColor;
@property (nonatomic, strong) UIColor * _Nullable buttonLastColor;
@end


SWIFT_CLASS("_TtC10fluigSDKUi14MfaRequestView")
@interface MfaRequestView : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end




@interface MfaRequestView (SWIFT_EXTENSION(fluigSDKUi))
@property (nonatomic, strong) UIImage * _Nullable backgroundImage;
@property (nonatomic, strong) UIColor * _Nonnull backgroundFirstColor;
@property (nonatomic, strong) UIColor * _Nonnull backgroundLastColor;
@property (nonatomic, strong) UIImage * _Nullable logoImage;
@property (nonatomic, copy) NSString * _Nullable pageControlTitle;
@property (nonatomic, strong) UIColor * _Nullable buttonFirstColor;
@property (nonatomic, strong) UIColor * _Nullable buttonLastColor;
@end




SWIFT_CLASS("_TtC10fluigSDKUi19PasswordRequestView")
@interface PasswordRequestView : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end




@interface PasswordRequestView (SWIFT_EXTENSION(fluigSDKUi))
@property (nonatomic, strong) UIImage * _Nullable backgroundImage;
@property (nonatomic, strong) UIColor * _Nonnull backgroundFirstColor;
@property (nonatomic, strong) UIColor * _Nonnull backgroundLastColor;
@property (nonatomic, strong) UIImage * _Nullable logoImage;
@property (nonatomic, copy) NSString * _Nullable pageControlTitle;
@property (nonatomic, strong) UIImage * _Nullable textFieldIcon;
@property (nonatomic, strong) UIColor * _Nullable buttonFirstColor;
@property (nonatomic, strong) UIColor * _Nullable buttonLastColor;
@end


SWIFT_CLASS("_TtC10fluigSDKUi19ServerSelectionView")
@interface ServerSelectionView : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end


@interface ServerSelectionView (SWIFT_EXTENSION(fluigSDKUi)) <FluigSDKPageViewDataSource>
- (NSArray<NSString *> * _Nonnull)getStrings SWIFT_WARN_UNUSED_RESULT;
@end

@class UITableView;
@class UITableViewCell;

@interface ServerSelectionView (SWIFT_EXTENSION(fluigSDKUi)) <UITableViewDataSource, UITableViewDelegate>
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)path SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end


@interface ServerSelectionView (SWIFT_EXTENSION(fluigSDKUi))
@property (nonatomic, strong) UIImage * _Nullable logoImage;
@property (nonatomic, copy) NSString * _Nullable title;
@end

























#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
